Use EVE_Manufacture_Planner
INSERT INTO MoonGoo(MGName,MGSize,MGGroup) VALUES('Atmospheric Gases',0.05,'Moon Materials')
INSERT INTO MoonGoo(MGName,MGSize,MGGroup) VALUES('Cadmium',0.05,'Moon Materials')
INSERT INTO MoonGoo(MGName,MGSize,MGGroup) VALUES('Caesium',0.05,'Moon Materials')
INSERT INTO MoonGoo(MGName,MGSize,MGGroup) VALUES('Chromium',0.05,'Moon Materials')
INSERT INTO MoonGoo(MGName,MGSize,MGGroup) VALUES('Cobalt',0.05,'Moon Materials')
INSERT INTO MoonGoo(MGName,MGSize,MGGroup) VALUES('Dysprosium',0.05,'Moon Materials')
INSERT INTO MoonGoo(MGName,MGSize,MGGroup) VALUES('Evaporite Deposits',0.05,'Moon Materials')
INSERT INTO MoonGoo(MGName,MGSize,MGGroup) VALUES('Hafnium',0.05,'Moon Materials')
INSERT INTO MoonGoo(MGName,MGSize,MGGroup) VALUES('Hydrocarbons',0.05,'Moon Materials')
INSERT INTO MoonGoo(MGName,MGSize,MGGroup) VALUES('Mercury',0.05,'Moon Materials')
INSERT INTO MoonGoo(MGName,MGSize,MGGroup) VALUES('Neodymium',0.05,'Moon Materials')
INSERT INTO MoonGoo(MGName,MGSize,MGGroup) VALUES('Platinum',0.05,'Moon Materials')
INSERT INTO MoonGoo(MGName,MGSize,MGGroup) VALUES('Promethium',0.05,'Moon Materials')
INSERT INTO MoonGoo(MGName,MGSize,MGGroup) VALUES('Scandium',0.05,'Moon Materials')
INSERT INTO MoonGoo(MGName,MGSize,MGGroup) VALUES('Silicates',0.05,'Moon Materials')
INSERT INTO MoonGoo(MGName,MGSize,MGGroup) VALUES('Technetium',0.05,'Moon Materials')
INSERT INTO MoonGoo(MGName,MGSize,MGGroup) VALUES('Thulium',0.05,'Moon Materials')
INSERT INTO MoonGoo(MGName,MGSize,MGGroup) VALUES('Titanium',0.05,'Moon Materials')
INSERT INTO MoonGoo(MGName,MGSize,MGGroup) VALUES('Tungsten',0.05,'Moon Materials')
INSERT INTO MoonGoo(MGName,MGSize,MGGroup) VALUES('Vanadium',0.05,'Moon Materials')
