USE EVE_Manufacture_Planner
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Alloyed Tritanium Bar',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Armor Plates',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Artificial Neural Network',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Broken Drone Transceivers',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Burned Logic Circuit',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Capacitor Console',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Charred Micro Circuit',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Conductive Polymer',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Conductive Thermoplastic',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Contaminated Lorentz Fluid',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Contaminated Nanite Compound',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Current Pump',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Damaged Artificial Neural Network',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Defective Current Pump',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Drone Transceiver',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Enhanced Ward Console',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Fried Interface Circuit',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Impetus Console',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Intact Armor Plates',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Intact Shield Emitter',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Interface Circuit',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Logic Circuit',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Lorentz Fluid',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Malfunctioning Shield Emitter',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Melted Capacitor Console',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Micro Circuit',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Nanite Compound',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Power Circuit',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Power Conduit',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Scorched Telemetry Processor',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Single-crystal Superalloy I-beam',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Smashed Trigger Unit',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Tangled Power Conduit',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Telemetry Processor',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Thruster Console',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Trigger Unit',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Tripped Power Circuit',0.01,'Salvaged Materials')
INSERT INTO Salvage(SALName,SALSize,SALGroup) VALUES('Ward Console',0.01,'Salvaged Materials')
