INSERT INTO Commodity(COName,COSize,COGroup) VALUES('R.A.M.- Ammunition Tech',0.04,'Tool')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('R.A.M.- Armor/Hull Tech',0.04,'Tool')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('R.A.M.- Battlecruiser Tech',0.04,'Tool')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('R.A.M.- Battleship Tech',0.04,'Tool')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('R.A.M.- Cruiser Tech',0.04,'Tool')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('R.A.M.- Cybernetics',0.04,'Tool')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('R.A.M.- Electronics',0.04,'Tool')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('R.A.M.- Energy Tech',0.04,'Tool')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('R.A.M.- Hypernet Tech',0.04,'Tool')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('R.A.M.- Industrial Tech',0.04,'Tool')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('R.A.M.- Pharmaceuticals',0.04,'Tool')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('R.A.M.- Platform Tech',0.04,'Tool')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('R.A.M.- Robotics',0.04,'Tool')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('R.A.M.- Shield Tech',0.04,'Tool')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('R.A.M.- Starship Tech',0.04,'Tool')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('R.A.M.- Weapon Tech',0.04,'Tool')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Shattered Villard Wheel',0.10,'Commodities')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Antimatter Reactor Unit',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Auto-Integrity Preservation Seal',16,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Singularity Radiation Convertor',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Trinary State Processor',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Zero-Point Field Manipulator',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Core Temperature Regulator',180,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Crystalline Carbonide Armor Plate',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Deflection Shield Emitter',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Electrolytic Capacitor Unit',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('EM Pulse Generator',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Fernite Carbide Composite Armor Plate',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Fusion Reactor Unit',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Fusion Thruster',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('G-O Trigger Neurolink Conduit',16,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Genetic Lock Preserver',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Genetic Mutation Inhibiter',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Genetic Safeguard Filter',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Genetic Structure Repairer',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Gravimetric Sensor Cluster',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Graviton Pulse Generator',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Graviton Reactor Unit',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Ion Thruster',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Ladar Sensor Cluster',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Laser Focusing Crystals',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Lattice Locked Dekaisogen',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Life Support Backup Unit',45,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Linear Shield Emitter',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Magnetometric Sensor Cluster',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Magpulse Thruster',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Nanoelectrical Microprocessor',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Nanomechanical Microprocessor',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Neurolink Enhancer Reservoir',400,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Nuclear Pulse Generator',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Nuclear Reactor Unit',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Oscillator Capacitor Unit',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Particle Accelerator Unit',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Photon Microprocessor',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Plasma Pulse Generator',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Plasma Thruster',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Programmable Purification Membrane',8000,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Pulse Shield Emitter',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Quantum Microprocessor',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('R-O Trigger Neurolink Conduit',16,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Radar Sensor Cluster',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Radiation Absorption Thruster',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('S-R Trigger Neurolink Conduit',16,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Scalar Capacitor Unit',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Singularity Radiation Convertor',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Spatial Attunement Unit',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Superconductor Rails',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Sustained Shield Emitter',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Tesseract Capacitor Unit',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Thermonuclear Trigger Unit',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Titanium Diborite Armor Plate',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Trinary State Processor',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Tungsten Carbide Armor Plate',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('U-C Trigger Neurolink Conduit',16,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Zero-Point Field Manipulator',1,'Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Absorption Thruster Array',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Armor Plates',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Capacitor Battery',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Cargo Bay',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Clone Vat Bay',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Computer System',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Construction Parts',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Core Temperature Regulator',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Corporate Hangar Bay',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Doomsday Weapon Mount',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Drone Bay',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Jump Bridge Array',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Jump Drive',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Launcher Hardpoint',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Power Generator',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Propulsion Engine',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Radiation Conversion Unit',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Sensor Cluster',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Shield Emitter',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Ship Maintenance Bay',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Siege Array',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Turret Hardpoint',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Ultratidal Entropic Mounting',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Enhanced Neurolink Protection Cell',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Neurolink Protection Cell',10000,'Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Antimatter Reactor Unit',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Crystalline Carbonide Armor Plate',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Deflection Shield Emitter',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Electrolytic Capacitor Unit',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital EM Pulse Generator',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Fernite Carbide Composite Armor Plate',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Fusion Reactor Unit',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Fusion Thruster',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Gravimetric Sensor Cluster',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Graviton Pulse Generator',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Graviton Reactor Unit',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Ion Thruster',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Ladar Sensor Cluster',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Laser Focusing Crystals',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Linear Shield Emitter',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Magnetometric Sensor Cluster',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Magpulse Thruster',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Nanoelectrical Microprocessor',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Nanomechanical Microprocessor',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Nuclear Pulse Generator',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Nuclear Reactor Unit',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Oscillator Capacitor Unit',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Particle Accelerator Unit',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Photon Microprocessor',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Plasma Pulse Generator',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Plasma Thruster',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Pulse Shield Emitter',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Quantum Microprocessor',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Radar Sensor Cluster',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Scalar Capacitor Unit',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Superconductor Rails',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Sustained Shield Emitter',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Tesseract Capacitor Unit',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Thermonuclear Trigger Unit',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Titanium Diborite Armor Plate',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Capital Tungsten Carbide Armor Plate',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Gravimetric-FTL Interlink Communicator',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Ladar-FTL Interlink Communicator',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Magnetometric-FTL Interlink Communicator',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Radar-FTL Interlink Communicator',10,'Advanced Capital Construction Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Structure Acceleration Coils',3000,'Structure Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Structure Advertisement Nexus',3000,'Structure Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Structure Construction Parts',3000,'Structure Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Structure Docking Bay',3000,'Structure Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Structure Electromagnetic Sensor',3000,'Structure Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Structure EXERT Conduit Coupler',3000,'Structure Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Structure Factory',3000,'Structure Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Structure Hangar Array',3000,'Structure Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Structure Laboratory',3000,'Structure Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Structure Market Network',3000,'Structure Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Structure Medical Center',3000,'Structure Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Structure Mission Network',3000,'Structure Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Structure Office Center',3000,'Structure Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Structure Repair Facility',3000,'Structure Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Structure Reprocessing Plant',3000,'Structure Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Structure Storage Bay',3000,'Structure Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Marines',2,'Livestock')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Janitor',3,'Livestock')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Covert Research Tools',0.10,'Miscellaneous')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Antikythera Element',0.10,'Unknown Components')
INSERT INTO Commodity(COName,COSize,COGroup) VALUES('Electronic Parts',1,'General')


