INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Caesarium Cadmide',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Carbon Fiber',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Carbon Polymers',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Ceramic Powder',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Crystalline Carbonide',0.01,'Composite')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Crystallite Alloy',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Dysporite',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Fermionic Condensates',0.01,'Composite')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Fernite Alloy',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Fernite Carbide',0.01,'Composite')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Ferrofluid',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Ferrogel',0.01,'Composite')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Fluxed Condensates',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Fulleride',0.01,'Composite')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Hexite',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Hyperflurite',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Hypersynaptic Fibers',0.01,'Composite')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Nanotransistors',0.01,'Composite')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Neo Mercurite',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Nonlinear Metamaterials',0.01,'Composite')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Oxy-Organic Solvents',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Phenolic Composites',0.01,'Composite')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Photonic Metamaterials',0.01,'Composite')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Plasmonic Metamaterials',0.01,'Composite')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Platinum Technite',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Pressurized Oxidizers',0.01,'Composite')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Promethium Mercurite',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Prometium',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Reinforced Carbon Fiber',0.01,'Composite')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Rolled Tungsten Alloy',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Silicon Diborite',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Solerium',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Sulfuric Acid',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Sylramic Fibers',0.01,'Composite')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Terahertz Metamaterials',0.01,'Composite')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Thermosetting Polymer',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Thulium Hafnite',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Titanium Carbide',0.01,'Composite')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Titanium Chromide',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Tungsten Carbide',0.01,'Composite')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Vanadium Hafnite',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Unrefined Caesarium Cadmide',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Unrefined Crystallite Alloy',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Unrefined Dysporite',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Unrefined Fernite Alloy',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Unrefined Ferrofluid',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Unrefined Fluxed Condensates',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Unrefined Hexite',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Unrefined Hyperflurite',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Unrefined Neo Mercurite',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Unrefined Platinum Technite',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Unrefined Promethium Mercurite',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Unrefined Prometium',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Unrefined Rolled Tungsten Alloy',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Unrefined Solerium',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Unrefined Thulium Hafnite',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Unrefined Titanium Chromide',0.20,'Intermediate Materials')
INSERT INTO ReactionMaterial(RMName,RMSize,RMGroup) VALUES('Unrefined Vanadium Hafnite',0.20,'Intermediate Materials')

