INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Armor Energizing Charge','Armor Command Burst Charges',0.01,1)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Armor Reinforcement Charge','Armor Command Burst Charges',0.01,2)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Rapid Repair Charge','Armor Command Burst Charges',0.01,3)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Inferno Auto-Targeting Cruise Missile I','Auto-Targeting Cruise Missile',0.05,4)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mjolnir Auto-Targeting Cruise Missile I','Auto-Targeting Cruise Missile',0.05,5)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Nova Auto-Targeting Cruise Missile I','Auto-Targeting Cruise Missile',0.05,6)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scourge Auto-Targeting Cruise Missile I','Auto-Targeting Cruise Missile',0.05,7)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Inferno Auto-Targeting Heavy Missile I','Auto-Targeting Heavy Missile',0.03,8)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mjolnir Auto-Targeting Heavy Missile I','Auto-Targeting Heavy Missile',0.03,9)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Nova Auto-Targeting Heavy Missile I','Auto-Targeting Heavy Missile',0.03,10)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scourge Auto-Targeting Heavy Missile I','Auto-Targeting Heavy Missile',0.03,11)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Inferno Auto-Targeting Light Missile I','Auto-Targeting Light Missile',0.02,12)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mjolnir Auto-Targeting Light Missile I','Auto-Targeting Light Missile',0.02,13)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Nova Auto-Targeting Light Missile I','Auto-Targeting Light Missile',0.02,14)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scourge Auto-Targeting Light Missile I','Auto-Targeting Light Missile',0.02,15)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Concussion Bomb','Bomb',75,16)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Electron Bomb','Bomb',75,17)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scorch Bomb','Bomb',75,18)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Shrapnel Bomb','Bomb',75,19)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Lockbreaker Bomb','Bomb ECM',75,20)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Void Bomb','Bomb Energy',75,21)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Cap Booster 100','Capacitor Booster Charge',4,22)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Cap Booster 150','Capacitor Booster Charge',6,23)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Cap Booster 200','Capacitor Booster Charge',8,24)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Cap Booster 25','Capacitor Booster Charge',1,25)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Cap Booster 3200','Capacitor Booster Charge',128,26)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Cap Booster 400','Capacitor Booster Charge',16,27)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Cap Booster 50','Capacitor Booster Charge',2,28)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Cap Booster 75','Capacitor Booster Charge',3,29)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Cap Booster 800','Capacitor Booster Charge',32,30)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Acolyte I','Combat Drone',5,31)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Berserker I','Combat Drone',25,32)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Bouncer I','Combat Drone',25,33)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Curator I','Combat Drone',25,34)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Garde I','Combat Drone',25,35)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Hammerhead I','Combat Drone',10,36)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Hobgoblin I','Combat Drone',5,37)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Hornet I','Combat Drone',5,38)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Infiltrator I','Combat Drone',10,39)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Ogre I','Combat Drone',25,40)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Praetor I','Combat Drone',25,41)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Valkyrie I','Combat Drone',10,42)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Vespa I','Combat Drone',10,43)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Warden I','Combat Drone',25,44)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Warrior I','Combat Drone',5,45)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Wasp I','Combat Drone',25,46)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Inferno Cruise Missile','Cruise Missile',0.05,47)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mjolnir Cruise Missile','Cruise Missile',0.05,48)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Nova Cruise Missile','Cruise Missile',0.05,49)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scourge Cruise Missile','Cruise Missile',0.05,50)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Defender Missile I','Defender Missiles',0.02,51)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Acolyte TD-300','Electronic Warfare Drone',5,52)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Berserker TP-900','Electronic Warfare Drone',25,53)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Hammerhead SD-600','Electronic Warfare Drone',10,54)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Hobgoblin SD-300','Electronic Warfare Drone',5,55)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Hornet EC-300','Electronic Warfare Drone',5,56)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Infiltrator TD-600','Electronic Warfare Drone',10,57)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Ogre SD-900','Electronic Warfare Drone',25,58)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Praetor TD-900','Electronic Warfare Drone',25,59)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Valkyrie TP-600','Electronic Warfare Drone',10,60)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Vespa EC-600','Electronic Warfare Drone',10,61)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Warrior TP-300','Electronic Warfare Drone',5,62)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Wasp EC-900','Electronic Warfare Drone',25,63)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Acolyte EV-300','Energy Neutralizer Drone',5,64)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Infiltrator EV-600','Energy Neutralizer Drone',10,65)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Praetor EV-900','Energy Neutralizer Drone',25,66)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Armor EM Resistance Script','Flex Armor Hardener Script',1,67)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Armor Explosive Resistance Script','Flex Armor Hardener Script',1,68)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Armor Kinetic Resistance Script','Flex Armor Hardener Script',1,69)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Armor Thermal Resistance Script','Flex Armor Hardener Script',1,70)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Shield EM Resistance Script','Flex Shield Hardener Script',1,71)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Shield Explosive Resistance Script','Flex Shield Hardener Script',1,72)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Shield Kinetic Resistance Script','Flex Shield Hardener Script',1,73)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Shield Thermal Resistance Script','Flex Shield Hardener Script',1,74)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Gamma L','Frequency Crystal',1,75)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Gamma XL','Frequency Crystal',1,76)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Infrared L','Frequency Crystal',1,77)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Infrared XL','Frequency Crystal',1,78)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Microwave L','Frequency Crystal',1,79)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Microwave XL','Frequency Crystal',1,80)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Multifrequency L','Frequency Crystal',1,81)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Multifrequency XL','Frequency Crystal',1,82)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Radio L','Frequency Crystal',1,83)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Radio XL','Frequency Crystal',1,84)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standard L','Frequency Crystal',1,85)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standard XL','Frequency Crystal',1,86)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Ultraviolet L','Frequency Crystal',1,87)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Ultraviolet XL','Frequency Crystal',1,88)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Xray L','Frequency Crystal',1,89)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Xray XL','Frequency Crystal',1,90)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Missile Precision Disruption Script','Guidance Disruption Script',1,91)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Missile Range Disruption Script','Guidance Disruption Script',1,92)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Heavy Guided Bomb','Guided Bomb',100,93)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Light Guided Bomb','Guided Bomb',100,94)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Inferno Heavy Assault Missile','Heavy Assault Missile',0.02,95)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mjolnir Heavy Assault Missile','Heavy Assault Missile',0.02,96)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Nova Heavy Assault Missile','Heavy Assault Missile',0.02,97)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scourge Heavy Assault Missile','Heavy Assault Missile',0.02,98)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Ametat I','Heavy Fighter',2000,99)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Antaeus I','Heavy Fighter',2000,100)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Cyclops I','Heavy Fighter',1800,101)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Gungnir I','Heavy Fighter',2000,102)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Malleus I','Heavy Fighter',1800,103)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mantis I','Heavy Fighter',1800,104)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Ametat I','Heavy Fighter',4000,105)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Antaeus I','Heavy Fighter',4000,106)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Cyclops I','Heavy Fighter',3600,107)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Gungnir I','Heavy Fighter',4000,108)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Malleus I','Heavy Fighter',3600,109)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Mantis I','Heavy Fighter',3600,110)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Termite I','Heavy Fighter',4000,111)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Tyrfing I','Heavy Fighter',3600,112)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Termite I','Heavy Fighter',2000,113)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Tyrfing I','Heavy Fighter',1800,114)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Inferno Heavy Missile','Heavy Missile',0.03,115)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mjolnir Heavy Missile','Heavy Missile',0.03,116)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Nova Heavy Missile','Heavy Missile',0.03,117)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scourge Heavy Missile','Heavy Missile',0.03,118)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Antimatter Charge L','Hybrid Charge',0.03,119)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Antimatter Charge M','Hybrid Charge',0.01,120)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Antimatter Charge S','Hybrid Charge',0,121)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Antimatter Charge XL','Hybrid Charge',0.13,122)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Iridium Charge L','Hybrid Charge',0.03,123)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Iridium Charge M','Hybrid Charge',0.01,124)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Iridium Charge S','Hybrid Charge',0,125)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Iridium Charge XL','Hybrid Charge',0.13,126)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Iron Charge L','Hybrid Charge',0.03,127)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Iron Charge M','Hybrid Charge',0.01,128)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Iron Charge S','Hybrid Charge',0,129)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Iron Charge XL','Hybrid Charge',0.13,130)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Lead Charge L','Hybrid Charge',0.03,131)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Lead Charge M','Hybrid Charge',0.01,132)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Lead Charge S','Hybrid Charge',0,133)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Lead Charge XL','Hybrid Charge',0.13,134)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Plutonium Charge L','Hybrid Charge',0.03,135)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Plutonium Charge M','Hybrid Charge',0.01,136)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Plutonium Charge S','Hybrid Charge',0,137)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Plutonium Charge XL','Hybrid Charge',0.13,138)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Thorium Charge L','Hybrid Charge',0.03,139)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Thorium Charge M','Hybrid Charge',0.01,140)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Thorium Charge S','Hybrid Charge',0,141)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Thorium Charge XL','Hybrid Charge',0.13,142)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Tungsten Charge L','Hybrid Charge',0.03,143)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Tungsten Charge M','Hybrid Charge',0.01,144)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Tungsten Charge S','Hybrid Charge',0,145)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Tungsten Charge XL','Hybrid Charge',0.13,146)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Uranium Charge L','Hybrid Charge',0.03,147)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Uranium Charge M','Hybrid Charge',0.01,148)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Uranium Charge S','Hybrid Charge',0,149)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Uranium Charge XL','Hybrid Charge',0.13,150)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Electronic Hardening Charge','Information Command Burst Charges',0.01,151)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Electronic Superiority Charge','Information Command Burst Charges',0.01,152)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Sensor Optimization Charge','Information Command Burst Charges',0.01,153)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Stasis Webification Probe','Interdiction Burst Probes',3,154)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Warp Disrupt Probe','Interdiction Probe',5,155)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Dragonfly I','Light Fighter',1000,156)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Einherji I','Light Fighter',1000,157)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Equite I','Light Fighter',800,158)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Firbolg I','Light Fighter',1000,159)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Gram I','Light Fighter',800,160)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Locust I','Light Fighter',800,161)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Satyr I','Light Fighter',800,162)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Dragonfly I','Light Fighter',2000,163)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Einherji I','Light Fighter',2000,164)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Equite I','Light Fighter',1600,165)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Firbolg I','Light Fighter',2000,166)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Gram I','Light Fighter',1600,167)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Locust I','Light Fighter',1600,168)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Satyr I','Light Fighter',1600,169)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Templar I','Light Fighter',2000,170)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Templar I','Light Fighter',1000,171)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Inferno Light Missile','Light Missile',0.02,172)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mjolnir Light Missile','Light Missile',0.02,173)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Nova Light Missile','Light Missile',0.02,174)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scourge Light Missile','Light Missile',0.02,175)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Heavy Armor Maintenance Bot I','Logistic Drone',25,176)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Heavy Hull Maintenance Bot I','Logistic Drone',25,177)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Heavy Shield Maintenance Bot I','Logistic Drone',25,178)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Light Armor Maintenance Bot I','Logistic Drone',5,179)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Light Hull Maintenance Bot I','Logistic Drone',5,180)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Light Shield Maintenance Bot I','Logistic Drone',5,181)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Armor Maintenance Bot I','Logistic Drone',10,182)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Hull Maintenance Bot I','Logistic Drone',10,183)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Shield Maintenance Bot I','Logistic Drone',10,184)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mercoxit Asteroid Mining Crystal Type A I','Mercoxit Mining Crystal',6,185)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mercoxit Asteroid Mining Crystal Type B I','Mercoxit Mining Crystal',6,186)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mercoxit Asteroid Mining Crystal Type C I','Mercoxit Mining Crystal',6,187)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Abyssal Asteroid Mining Crystal Type A I','Mining Crystal',10,188)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Abyssal Asteroid Mining Crystal Type B I','Mining Crystal',10,189)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Abyssal Asteroid Mining Crystal Type C I','Mining Crystal',10,190)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Coherent Asteroid Mining Crystal Type A I','Mining Crystal',6,191)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Coherent Asteroid Mining Crystal Type B I','Mining Crystal',6,192)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Coherent Asteroid Mining Crystal Type C I','Mining Crystal',6,193)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Common Moon Mining Crystal Type A I','Mining Crystal',6,194)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Common Moon Mining Crystal Type B I','Mining Crystal',6,195)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Common Moon Mining Crystal Type C I','Mining Crystal',6,196)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Complex Asteroid Mining Crystal Type A I','Mining Crystal',6,197)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Complex Asteroid Mining Crystal Type B I','Mining Crystal',6,198)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Complex Asteroid Mining Crystal Type C I','Mining Crystal',6,199)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Exceptional Moon Mining Crystal Type A I','Mining Crystal',6,200)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Exceptional Moon Mining Crystal Type B I','Mining Crystal',6,201)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Exceptional Moon Mining Crystal Type C I','Mining Crystal',6,202)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Rare Moon Mining Crystal Type A I','Mining Crystal',6,203)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Rare Moon Mining Crystal Type B I','Mining Crystal',6,204)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Rare Moon Mining Crystal Type C I','Mining Crystal',6,205)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Simple Asteroid Mining Crystal Type A I','Mining Crystal',6,206)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Simple Asteroid Mining Crystal Type B I','Mining Crystal',6,207)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Simple Asteroid Mining Crystal Type C I','Mining Crystal',6,208)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Ubiquitous Moon Mining Crystal Type A I','Mining Crystal',6,209)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Ubiquitous Moon Mining Crystal Type B I','Mining Crystal',6,210)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Ubiquitous Moon Mining Crystal Type C I','Mining Crystal',6,211)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Uncommon Moon Mining Crystal Type A I','Mining Crystal',6,212)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Uncommon Moon Mining Crystal Type B I','Mining Crystal',6,213)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Uncommon Moon Mining Crystal Type C I','Mining Crystal',6,214)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Variegated Asteroid Mining Crystal Type A I','Mining Crystal',6,215)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Variegated Asteroid Mining Crystal Type B I','Mining Crystal',6,216)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Variegated Asteroid Mining Crystal Type C I','Mining Crystal',6,217)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Civilian Mining Drone','Mining Drone',5,218)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Ice Harvesting Drone I','Mining Drone',50,219)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mining Drone I','Mining Drone',5,220)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mining Equipment Preservation Charge','Mining Foreman Burst Charges',0.01,221)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mining Laser Field Enhancement Charge','Mining Foreman Burst Charges',0.01,222)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mining Laser Optimization Charge','Mining Foreman Burst Charges',0.01,223)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Missile Precision Script','Missile Guidance Script',1,224)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Missile Range Script','Missile Guidance Script',1,225)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Carbonized Lead L','Projectile Ammo',0.03,226)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Carbonized Lead M','Projectile Ammo',0.01,227)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Carbonized Lead S','Projectile Ammo',0,228)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Carbonized Lead XL','Projectile Ammo',0.13,229)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Depleted Uranium L','Projectile Ammo',0.03,230)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Depleted Uranium M','Projectile Ammo',0.01,231)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Depleted Uranium S','Projectile Ammo',0,232)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Depleted Uranium XL','Projectile Ammo',0.13,233)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('EMP L','Projectile Ammo',0.03,234)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('EMP M','Projectile Ammo',0.01,235)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('EMP S','Projectile Ammo',0,236)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('EMP XL','Projectile Ammo',0.13,237)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Fusion L','Projectile Ammo',0.03,238)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Fusion M','Projectile Ammo',0.01,239)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Fusion S','Projectile Ammo',0,240)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Fusion XL','Projectile Ammo',0.13,241)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Nuclear L','Projectile Ammo',0.03,242)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Nuclear M','Projectile Ammo',0.01,243)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Nuclear S','Projectile Ammo',0,244)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Nuclear XL','Projectile Ammo',0.25,245)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Phased Plasma L','Projectile Ammo',0.03,246)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Phased Plasma M','Projectile Ammo',0.01,247)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Phased Plasma S','Projectile Ammo',0,248)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Phased Plasma XL','Projectile Ammo',0.13,249)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Proton L','Projectile Ammo',0.03,250)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Proton M','Projectile Ammo',0.01,251)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Proton S','Projectile Ammo',0,252)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Proton XL','Projectile Ammo',0.13,253)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Titanium Sabot L','Projectile Ammo',0.03,254)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Titanium Sabot M','Projectile Ammo',0.01,255)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Titanium Sabot S','Projectile Ammo',0,256)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Titanium Sabot XL','Projectile Ammo',0.13,257)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Inferno Rocket','Rocket',0.01,258)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mjolnir Rocket','Rocket',0.01,259)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Nova Rocket','Rocket',0.01,260)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scourge Rocket','Rocket',0.01,261)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Salvage Drone I','Salvage Drone',5,262)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Combat Scanner Probe I','Scanner Probe',1,263)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Core Scanner Probe I','Scanner Probe',0.1,264)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('ECCM Script','Sensor Booster Script',1,265)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scan Resolution Script','Sensor Booster Script',1,266)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Targeting Range Script','Sensor Booster Script',1,267)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scan Resolution Dampening Script','Sensor Dampener Script',1,268)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Targeting Range Dampening Script','Sensor Dampener Script',1,269)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Active Shielding Charge','Shield Command Burst Charges',0.01,270)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Shield Extension Charge','Shield Command Burst Charges',0.01,271)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Shield Harmonizing Charge','Shield Command Burst Charges',0.01,272)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Evasive Maneuvers Charge','Skirmish Command Burst Charges',0.01,273)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Interdiction Maneuvers Charge','Skirmish Command Burst Charges',0.01,274)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Rapid Deployment Charge','Skirmish Command Burst Charges',0.01,275)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Berserker SW-900','Stasis Webifying Drone',25,276)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Valkyrie SW-600','Stasis Webifying Drone',10,277)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Warrior SW-300','Stasis Webifying Drone',5,278)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Super-heavy Torpedo','Structure Anti-Capital Missile',0.5,279)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup XL Cruise Missile','Structure Anti-Capital Missile',0.5,280)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Cruise Missile','Structure Anti-Subcapital Missile',0.5,281)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Heavy Missile','Structure Anti-Subcapital Missile',0.5,282)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Light Missile','Structure Anti-Subcapital Missile',0.5,283)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Gravimetric ECM Script','Structure ECM script',1,284)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Ladar ECM Script','Structure ECM script',1,285)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Magnetometric ECM Script','Structure ECM script',1,286)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Radar ECM Script','Structure ECM script',1,287)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Focused Warp Scrambling Script','Structure Warp Disruptor Script',1,288)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Cenobite I','Support Fighter',3000,289)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Dromi I','Support Fighter',3000,290)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scarab I','Support Fighter',3000,291)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Siren I','Support Fighter',3000,292)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Cenobite I','Support Fighter',6000,293)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Dromi I','Support Fighter',6000,294)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Scarab I','Support Fighter',6000,295)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Standup Siren I','Support Fighter',6000,296)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Discovery Survey Probe I','Survey Probe',10,297)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Gaze Survey Probe I','Survey Probe',5,298)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Quest Survey Probe I','Survey Probe',5,299)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Inferno Torpedo','Torpedo',0.05,300)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mjolnir Torpedo','Torpedo',0.05,301)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Nova Torpedo','Torpedo',0.05,302)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scourge Torpedo','Torpedo',0.05,303)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Optimal Range Disruption Script','Tracking Disruption Script',1,304)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Tracking Speed Disruption Script','Tracking Disruption Script',1,305)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Optimal Range Script','Tracking Script',1,306)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Tracking Speed Script','Tracking Script',1,307)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Focused Warp Disruption Script','Warp Disruption Script',1,308)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Focused Warp Scrambling Script','Warp Disruption Script',1,309)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Inferno XL Cruise Missile','XL Cruise Missile',0.3,310)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mjolnir XL Cruise Missile','XL Cruise Missile',0.3,311)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Nova XL Cruise Missile','XL Cruise Missile',0.3,312)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scourge XL Cruise Missile','XL Cruise Missile',0.3,313)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Inferno XL Torpedo','XL Torpedo',0.3,314)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mjolnir XL Torpedo','XL Torpedo',0.3,315)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Nova XL Torpedo','XL Torpedo',0.3,316)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scourge XL Torpedo','XL Torpedo',0.3,317)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Ancillary Armor Repairer','Ancillary Armor Repairer',1000,318)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Ancillary Armor Repairer','Ancillary Armor Repairer',50,319)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Ancillary Armor Repairer','Ancillary Armor Repairer',10,320)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small Ancillary Armor Repairer','Ancillary Armor Repairer',5,321)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Ancillary Remote Armor Repairer','Ancillary Remote Armor Repairer',1000,322)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Ancillary Remote Armor Repairer','Ancillary Remote Armor Repairer',25,323)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Ancillary Remote Armor Repairer','Ancillary Remote Armor Repairer',10,324)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small Ancillary Remote Armor Repairer','Ancillary Remote Armor Repairer',5,325)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Ancillary Remote Shield Booster','Ancillary Remote Shield Booster',1000,326)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Ancillary Remote Shield Booster','Ancillary Remote Shield Booster',25,327)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Ancillary Remote Shield Booster','Ancillary Remote Shield Booster',10,328)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small Ancillary Remote Shield Booster','Ancillary Remote Shield Booster',5,329)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Ancillary Shield Booster','Ancillary Shield Booster',1000,330)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Ancillary Shield Booster','Ancillary Shield Booster',25,331)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Ancillary Shield Booster','Ancillary Shield Booster',10,332)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small Ancillary Shield Booster','Ancillary Shield Booster',5,333)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('X-Large Ancillary Shield Booster','Ancillary Shield Booster',50,334)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('EM Coating I','Armor Coating',5,335)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Layered Coating I','Armor Coating',5,336)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('EM Armor Hardener I','Armor Hardener',5,337)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Explosive Armor Hardener I','Armor Hardener',5,338)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Kinetic Armor Hardener I','Armor Hardener',5,339)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Thermal Armor Hardener I','Armor Hardener',5,340)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('100mm Steel Plates I','Armor Plate',5,341)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('1600mm Steel Plates I','Armor Plate',20,342)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('200mm Steel Plates I','Armor Plate',10,343)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('25000mm Steel Plates I','Armor Plate',1000,344)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('400mm Steel Plates I','Armor Plate',25,345)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('800mm Steel Plates I','Armor Plate',50,346)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital ACM Compact Armor Repairer','Armor Repair Unit',1000,347)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Armor Repairer I','Armor Repair Unit',1000,348)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital I-a Enduring Armor Repairer','Armor Repair Unit',1000,349)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Civilian Armor Repairer','Armor Repair Unit',5,350)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Armor Repairer I','Armor Repair Unit',50,351)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Armor Repairer I','Armor Repair Unit',10,352)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small Armor Repairer I','Armor Repair Unit',5,353)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Reactive Armor Hardener','Armor Resistance Shift Hardener',25,354)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Auto Targeting System I','Automated Targeting System',5,355)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Micro Auxiliary Power Core I','Auxiliary Power Core',20,356)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Ballistic Control System I','Ballistic Control system',5,357)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Burst Jammer I','Burst Jammer',5,358)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('ECM Jammer Burst Projector','Burst Projectors',2000,359)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Energy Neutralization Burst Projector','Burst Projectors',2000,360)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Sensor Dampening Burst Projector','Burst Projectors',2000,361)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Stasis Webification Burst Projector','Burst Projectors',2000,362)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Target Illumination Burst Projector','Burst Projectors',2000,363)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Warp Disruption Burst Projector','Burst Projectors',2000,364)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Weapon Disruption Burst Projector','Burst Projectors',2000,365)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Cap Battery I','Capacitor Battery',1000,366)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Cap Battery I','Capacitor Battery',15,367)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Cap Battery I','Capacitor Battery',10,368)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small Cap Battery I','Capacitor Battery',5,369)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Capacitor Booster I','Capacitor Booster',1000,370)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Heavy Capacitor Booster I','Capacitor Booster',20,371)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Capacitor Booster I','Capacitor Booster',10,372)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small Capacitor Booster I','Capacitor Booster',5,373)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capacitor Flux Coil I','Capacitor Flux Coil',5,374)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capacitor Power Relay I','Capacitor Power Relay',5,375)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Cap Recharger I','Capacitor Recharger',5,376)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Networked Sensor Array','Capital Sensor Array',1000,377)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Cargo Scanner I','Cargo Scanner',5,378)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Prototype Cloaking Device I','Cloaking Device',100,379)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Clone Vat Bay I','Clone Vat Bay',4000,380)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Tactical Capsuleer Recloner','Clone Vat Bay',4000,381)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Armor Command Burst I','Command Burst',60,382)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Information Command Burst I','Command Burst',60,383)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mining Foreman Burst I','Command Burst',60,384)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Shield Command Burst I','Command Burst',60,385)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Skirmish Command Burst I','Command Burst',60,386)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Asteroid Ore Compressor I','Compressors',2000,387)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Gas Compressor I','Compressors',2000,388)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Ice Compressor I','Compressors',2000,389)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Mercoxit Compressor I','Compressors',2000,390)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Moon Ore Compressor I','Compressors',2000,391)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Asteroid Ore Compressor I','Compressors',1000,392)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Gas Compressor I','Compressors',1000,393)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Ice Compressor I','Compressors',1000,394)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Mercoxit Compressor I','Compressors',1000,395)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Moon Ore Compressor I','Compressors',1000,396)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Asteroid Ore Compressor I','Compressors',500,397)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Gas Compressor I','Compressors',500,398)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Covert Jump Portal Generator I','Covert Jump Portal Generator',125,399)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Co-Processor I','CPU Enhancer',5,400)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Covert Cynosural Field Generator I','Cynosural Field Generator',25,401)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Cynosural Field Generator I','Cynosural Field Generator',50,402)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Industrial Cynosural Field Generator','Cynosural Field Generator',25,403)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Assault Damage Control I','Damage Control',5,404)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Emergency Hull Energizer I','Damage Control',2000,405)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Implacable Compact Emergency Hull Energizer','Damage Control',2000,406)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Indefatigable Enduring Emergency Hull Energizer','Damage Control',2000,407)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Civilian Damage Control','Damage Control',5,408)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Damage Control I','Damage Control',5,409)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Data Analyzer I','Data Miners',5,410)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Relic Analyzer I','Data Miners',5,411)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Drone Link Augmentor I','Drone Control Range Module',25,412)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Drone Damage Amplifier I','Drone Damage Modules',5,413)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Drone Navigation Computer I','Drone Navigation Computer',25,414)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Omnidirectional Tracking Enhancer I','Drone Tracking Enhancer',5,415)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Omnidirectional Tracking Link I','Drone Tracking Modules',5,416)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Gravimetric ECM I','ECM',5,417)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Ladar ECM I','ECM',5,418)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Magnetometric ECM I','ECM',5,419)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Multispectral ECM I','ECM',5,420)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Radar ECM I','ECM',5,421)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Signal Distortion Amplifier I','ECM Stabilizer',5,422)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('EM Energized Membrane I','Energized Armor Membrane',5,423)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Explosive Energized Membrane I','Energized Armor Membrane',5,424)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Kinetic Energized Membrane I','Energized Armor Membrane',5,425)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Layered Energized Membrane I','Energized Armor Membrane',5,426)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Multispectrum Energized Membrane I','Energized Armor Membrane',5,427)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Thermal Energized Membrane I','Energized Armor Membrane',5,428)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Energy Neutralizer I','Energy Neutralizer',1000,429)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Heavy Energy Neutralizer I','Energy Neutralizer',50,430)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Energy Neutralizer I','Energy Neutralizer',5,431)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small Energy Neutralizer I','Energy Neutralizer',5,432)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Energy Nosferatu I','Energy Nosferatu',1000,433)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Heavy Energy Nosferatu I','Energy Nosferatu',5,434)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Energy Nosferatu I','Energy Nosferatu',5,435)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small Energy Nosferatu I','Energy Nosferatu',5,436)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Afocal Precise Dual Giga Beam Laser','Energy Weapon',1000,437)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Afocal Precise Dual Giga Pulse Laser','Energy Weapon',1000,438)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Afocal Precise Quad Mega Pulse Laser','Energy Weapon',1000,439)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Anode Scoped Dual Giga Beam Laser','Energy Weapon',1000,440)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Anode Scoped Dual Giga Pulse Laser','Energy Weapon',1000,441)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Anode Scoped Quad Mega Pulse Laser','Energy Weapon',1000,442)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Dual Giga Beam Laser I','Energy Weapon',1000,443)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Dual Giga Pulse Laser I','Energy Weapon',1000,444)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Dual Heavy Beam Laser I','Energy Weapon',50,445)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Dual Heavy Pulse Laser I','Energy Weapon',20,446)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Dual Light Beam Laser I','Energy Weapon',5,447)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Dual Light Pulse Laser I','Energy Weapon',5,448)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Focused Medium Beam Laser I','Energy Weapon',10,449)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Focused Medium Pulse Laser I','Energy Weapon',10,450)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Gatling Pulse Laser I','Energy Weapon',5,451)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Heavy Beam Laser I','Energy Weapon',25,452)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Heavy Pulse Laser I','Energy Weapon',25,453)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mega Beam Laser I','Energy Weapon',50,454)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mega Pulse Laser I','Energy Weapon',50,455)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Modal Enduring Dual Giga Beam Laser','Energy Weapon',1000,456)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Modal Enduring Dual Giga Pulse Laser','Energy Weapon',1000,457)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Modal Enduring Quad Mega Pulse Laser','Energy Weapon',1000,458)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Modulated Compact Dual Giga Beam Laser','Energy Weapon',1000,459)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Modulated Compact Dual Giga Pulse Laser','Energy Weapon',1000,460)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Modulated Compact Quad Mega Pulse Laser','Energy Weapon',1000,461)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Quad Light Beam Laser I','Energy Weapon',10,462)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Quad Mega Pulse Laser I','Energy Weapon',1000,463)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small Focused Beam Laser I','Energy Weapon',5,464)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small Focused Pulse Laser I','Energy Weapon',5,465)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Tachyon Beam Laser I','Energy Weapon',50,466)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Entosis Link I','Entosis Link',20,467)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Civilian Expanded Cargohold','Expanded Cargohold',5,468)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Expanded Cargohold I','Expanded Cargohold',5,469)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Fighter Support Unit I','Fighter Support Unit',1000,470)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Flex Armor Hardener I','Flex Armor Hardener',1000,471)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Flex Shield Hardener I','Flex Shield Hardener',1000,472)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Gas Cloud Harvester I','Gas Cloud Harvesters',5,473)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Gas Cloud Scoop I','Gas Cloud Scoops',5,474)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Gyrostabilizer I','Gyrostabilizer',5,475)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Heat Sink I','Heat Sink',5,476)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Hull Repairer I','Hull Repair Unit',1000,477)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital I-b Enduring Hull Repairer','Hull Repair Unit',1000,478)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital IEF Compact Hull Repairer','Hull Repair Unit',1000,479)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Hull Repairer I','Hull Repair Unit',50,480)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Hull Repairer I','Hull Repair Unit',25,481)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small Hull Repairer I','Hull Repair Unit',12.5,482)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('125mm Railgun I','Hybrid Weapon',5,483)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('150mm Railgun I','Hybrid Weapon',5,484)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('200mm Railgun I','Hybrid Weapon',10,485)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('250mm Railgun I','Hybrid Weapon',25,486)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('350mm Railgun I','Hybrid Weapon',50,487)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('425mm Railgun I','Hybrid Weapon',50,488)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('75mm Gatling Rail I','Hybrid Weapon',5,489)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Anode Scoped Ion Siege Blaster','Hybrid Weapon',1000,490)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Anode Scoped Triple Neutron Blaster Cannon','Hybrid Weapon',1000,491)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Carbide Compact Dual 1000mm Railgun','Hybrid Weapon',1000,492)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Compressed Enduring Dual 1000mm Railgun','Hybrid Weapon',1000,493)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Dual 1000mm Railgun I','Hybrid Weapon',1000,494)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Dual 150mm Railgun I','Hybrid Weapon',10,495)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Dual 250mm Railgun I','Hybrid Weapon',20,496)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Electron Blaster Cannon I','Hybrid Weapon',50,497)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Heavy Electron Blaster I','Hybrid Weapon',10,498)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Heavy Ion Blaster I','Hybrid Weapon',10,499)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Heavy Neutron Blaster I','Hybrid Weapon',25,500)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Ion Blaster Cannon I','Hybrid Weapon',50,501)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Ion Siege Blaster I','Hybrid Weapon',1000,502)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Light Electron Blaster I','Hybrid Weapon',5,503)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Light Ion Blaster I','Hybrid Weapon',5,504)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Light Neutron Blaster I','Hybrid Weapon',5,505)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Limited Precise Ion Siege Blaster','Hybrid Weapon',1000,506)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Limited Precise Triple Neutron Blaster Cannon','Hybrid Weapon',1000,507)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Modal Enduring Ion Siege Blaster','Hybrid Weapon',1000,508)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Modal Enduring Triple Neutron Blaster Cannon','Hybrid Weapon',1000,509)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Neutron Blaster Cannon I','Hybrid Weapon',50,510)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Prototype Precise Dual 1000mm Railgun','Hybrid Weapon',1000,511)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Regulated Compact Ion Siege Blaster','Hybrid Weapon',1000,512)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Regulated Compact Triple Neutron Blaster Cannon','Hybrid Weapon',1000,513)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scout Scoped Dual 1000mm Railgun','Hybrid Weapon',1000,514)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Triple Neutron Blaster Cannon I','Hybrid Weapon',1000,515)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Industrial Jump Portal Generator I','Industrial Jump Portal Generator',5000,516)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Inertial Stabilizers I','Inertial Stabilizer',5,517)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Interdiction Nullifier I','Interdiction Nullifier',5,518)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Interdiction Sphere Launcher I','Interdiction Sphere Launcher',50,519)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Experimental Jump Drive Economizer','Jump Drive Economizer',3500,520)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Limited Jump Drive Economizer','Jump Drive Economizer',3500,521)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Prototype Jump Drive Economizer','Jump Drive Economizer',3500,522)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Jump Portal Generator I','Jump Portal Generator',10000,523)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Magnetic Field Stabilizer I','Magnetic Field Stabilizer',5,524)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Zero-Point Mass Entangler','Mass Entanglers',50,525)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Micro Jump Drive','Micro Jump Drive',10,526)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Micro Jump Drive','Micro Jump Drive',10,527)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Micro Jump Field Generator','Micro Jump Field Generators',10,528)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Deep Core Mining Laser I','Mining Laser',5,529)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Ice Mining Laser I','Mining Laser',5,530)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Miner I','Mining Laser',5,531)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Ice Harvester Upgrade I','Mining Upgrade',5,532)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mining Laser Upgrade I','Mining Upgrade',5,533)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Missile Guidance Computer I','Missile Guidance Computer',5,534)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Missile Guidance Enhancer I','Missile Guidance Enhancer',5,535)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Bomb Launcher I','Missile Launcher Bomb',50,536)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Cruise Missile Launcher I','Missile Launcher Cruise',20,537)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Defender Launcher I','Missile Launcher Defender',5,538)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Heavy Missile Launcher I','Missile Launcher Heavy',10,539)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Heavy Assault Missile Launcher I','Missile Launcher Heavy Assault',10,540)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Light Missile Launcher I','Missile Launcher Light',5,541)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Rapid Heavy Missile Launcher I','Missile Launcher Rapid Heavy',20,542)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Rapid Light Missile Launcher I','Missile Launcher Rapid Light',10,543)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Rapid Torpedo Launcher I','Missile Launcher Rapid Torpedo',1000,544)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Rocket Launcher I','Missile Launcher Rocket',5,545)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Torpedo Launcher I','Missile Launcher Torpedo',20,546)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Arbalest Compact XL Cruise Missile Launcher','Missile Launcher XL Cruise',1000,547)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('TE-2100 Ample XL Cruise Missile Launcher','Missile Launcher XL Cruise',1000,548)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('XL Cruise Missile Launcher I','Missile Launcher XL Cruise',1000,549)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Arbalest Compact XL Torpedo Launcher','Missile Launcher XL Torpedo',1000,550)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('TE-2100 Ample XL Torpedo Launcher','Missile Launcher XL Torpedo',1000,551)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('XL Torpedo Launcher I','Missile Launcher XL Torpedo',1000,552)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Nanofiber Internal Structure I','Nanofiber Internal Structure',5,553)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Overdrive Injector System I','Overdrive Injector System',5,554)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Passive Targeter I','Passive Targeting System',25,555)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Power Diagnostic System I','Power Diagnostic System',5,556)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('1200mm Artillery Cannon I','Projectile Weapon',50,557)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('125mm Gatling AutoCannon I','Projectile Weapon',5,558)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('1400mm Howitzer Artillery I','Projectile Weapon',50,559)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('150mm Light AutoCannon I','Projectile Weapon',5,560)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('200mm AutoCannon I','Projectile Weapon',5,561)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('220mm Vulcan AutoCannon I','Projectile Weapon',10,562)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('250mm Light Artillery Cannon I','Projectile Weapon',5,563)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('280mm Howitzer Artillery I','Projectile Weapon',5,564)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('425mm AutoCannon I','Projectile Weapon',10,565)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('650mm Artillery Cannon I','Projectile Weapon',25,566)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('720mm Howitzer Artillery I','Projectile Weapon',25,567)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('800mm Repeating Cannon I','Projectile Weapon',25,568)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Carbide Compact Quad 3500mm Siege Artillery','Projectile Weapon',1000,569)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Dual 180mm AutoCannon I','Projectile Weapon',10,570)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Dual 425mm AutoCannon I','Projectile Weapon',20,571)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Dual 650mm Repeating Cannon I','Projectile Weapon',50,572)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Gallium Ample Quad 3500mm Siege Artillery','Projectile Weapon',1000,573)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Hexa 2500mm Repeating Cannon I','Projectile Weapon',1000,574)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Prototype Precise Quad 3500mm Siege Artillery','Projectile Weapon',1000,575)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Quad 3500mm Siege Artillery I','Projectile Weapon',1000,576)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Quad 800mm Repeating Cannon I','Projectile Weapon',1000,577)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scout Scoped Quad 3500mm Siege Artillery','Projectile Weapon',1000,578)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('10000MN Afterburner I','Propulsion Module',1000,579)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('10000MN Monopropellant Enduring Afterburner','Propulsion Module',1000,580)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('10000MN Y-S8 Compact Afterburner','Propulsion Module',1000,581)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('100MN Afterburner I','Propulsion Module',50,582)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('10MN Afterburner I','Propulsion Module',25,583)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('1MN Afterburner I','Propulsion Module',5,584)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('50000MN Cold-Gas Enduring Microwarpdrive','Propulsion Module',1000,585)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('50000MN Microwarpdrive I','Propulsion Module',1000,586)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('50000MN Quad LiF Restrained Microwarpdrive','Propulsion Module',1000,587)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('50000MN Y-T8 Compact Microwarpdrive','Propulsion Module',1000,588)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('500MN Microwarpdrive I','Propulsion Module',50,589)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('50MN Microwarpdrive I','Propulsion Module',25,590)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('5MN Microwarpdrive I','Propulsion Module',10,591)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Reactor Control Unit I','Reactor Control Unit',5,592)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Reinforced Bulkheads I','Reinforced Bulkhead',25,593)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Coaxial Compact Remote Armor Repairer','Remote Armor Repairer',1000,594)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital I-ax Enduring Remote Armor Repairer','Remote Armor Repairer',1000,595)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Remote Armor Repairer I','Remote Armor Repairer',1000,596)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Solace Scoped Remote Armor Repairer','Remote Armor Repairer',1000,597)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Remote Armor Repairer I','Remote Armor Repairer',25,598)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Remote Armor Repairer I','Remote Armor Repairer',10,599)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Remote Capacitor Transmitter I','Remote Capacitor Transmitter',1000,600)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Remote Capacitor Transmitter I','Remote Capacitor Transmitter',25,601)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Remote Capacitor Transmitter I','Remote Capacitor Transmitter',10,602)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small Remote Capacitor Transmitter I','Remote Capacitor Transmitter',5,603)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Remote Hull Repairer I','Remote Hull Repairer',1000,604)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Remote Hull Repairer I','Remote Hull Repairer',50,605)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Remote Hull Repairer I','Remote Hull Repairer',10,606)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small Remote Hull Repairer I','Remote Hull Repairer',5,607)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Remote Sensor Booster I','Remote Sensor Booster',25,608)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Asymmetric Enduring Remote Shield Booster','Remote Shield Booster',1000,609)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Murky Compact Remote Shield Booster','Remote Shield Booster',1000,610)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Remote Shield Booster I','Remote Shield Booster',1000,611)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital S95a Scoped Remote Shield Booster','Remote Shield Booster',1000,612)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Remote Shield Booster I','Remote Shield Booster',25,613)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Remote Shield Booster I','Remote Shield Booster',10,614)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small Remote Shield Booster I','Remote Shield Booster',5,615)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Remote Tracking Computer I','Remote Tracking Computer',25,616)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Salvager I','Salvager',5,617)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Core Probe Launcher I','Scan Probe Launcher',5,618)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Expanded Probe Launcher I','Scan Probe Launcher',5,619)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scan Pinpointing Array I','Scanning Upgrade',5,620)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scan Rangefinding Array I','Scanning Upgrade',5,621)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scan Acquisition Array I','Scanning Upgrade Time',5,622)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Sensor Booster I','Sensor Booster',5,623)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Remote Sensor Dampener I','Sensor Dampener',5,624)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Shield Boost Amplifier I','Shield Boost Amplifier',5,625)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital C-5L Compact Shield Booster','Shield Booster',1000,626)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Clarity Ward Enduring Shield Booster','Shield Booster',1000,627)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Shield Booster I','Shield Booster',1000,628)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Civilian Shield Booster','Shield Booster',5,629)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Shield Booster I','Shield Booster',25,630)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Shield Booster I','Shield Booster',10,631)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small Shield Booster I','Shield Booster',5,632)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('X-Large Shield Booster I','Shield Booster',50,633)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Azeotropic Restrained Shield Extender','Shield Extender',1000,634)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital F-S9 Regolith Compact Shield Extender','Shield Extender',1000,635)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Shield Extender I','Shield Extender',1000,636)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Shield Extender I','Shield Extender',20,637)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Shield Extender I','Shield Extender',10,638)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small Shield Extender I','Shield Extender',5,639)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Shield Flux Coil I','Shield Flux Coil',5,640)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Civilian EM Shield Hardener','Shield Hardener',5,641)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Civilian Explosive Shield Hardener','Shield Hardener',5,642)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Civilian Kinetic Shield Hardener','Shield Hardener',5,643)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('EM Shield Hardener I','Shield Hardener',5,644)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Explosive Shield Hardener I','Shield Hardener',5,645)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Kinetic Shield Hardener I','Shield Hardener',5,646)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Multispectrum Shield Hardener I','Shield Hardener',5,647)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Thermal Shield Hardener I','Shield Hardener',5,648)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Shield Power Relay I','Shield Power Relay',5,649)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Shield Recharger I','Shield Recharger',5,650)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('EM Shield Amplifier I','Shield Resistance Amplifier',5,651)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Explosive Shield Amplifier I','Shield Resistance Amplifier',5,652)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Kinetic Shield Amplifier I','Shield Resistance Amplifier',5,653)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Thermal Shield Amplifier I','Shield Resistance Amplifier',5,654)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Ship Scanner I','Ship Scanner',5,655)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Bastion Module I','Siege Module',200,656)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Industrial Core I','Siege Module',1000,657)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Industrial Core I','Siege Module',3500,658)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Siege Module I','Siege Module',1000,659)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Triage Module I','Siege Module',1000,660)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Signal Amplifier I','Signal Amplifier',5,661)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Signature Radius Suppressor I','Signature Suppressor',5,662)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large EMP Smartbomb I','Smart Bomb',50,663)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Graviton Smartbomb I','Smart Bomb',50,664)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Plasma Smartbomb I','Smart Bomb',50,665)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Large Proton Smartbomb I','Smart Bomb',50,666)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium EMP Smartbomb I','Smart Bomb',25,667)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Graviton Smartbomb I','Smart Bomb',25,668)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Plasma Smartbomb I','Smart Bomb',25,669)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Medium Proton Smartbomb I','Smart Bomb',25,670)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small EMP Smartbomb I','Smart Bomb',12.5,671)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small Graviton Smartbomb I','Smart Bomb',12.5,672)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small Proton Smartbomb I','Smart Bomb',12.5,673)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Heavy Stasis Grappler I','Stasis Grappler',50,674)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Civilian Stasis Webifier','Stasis Web',5,675)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Stasis Webifier I','Stasis Web',5,676)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Ice Harvester I','Strip Miner',25,677)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Strip Miner I','Strip Miner',25,678)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('’Aurora Ominae’ Thermal Doomsday','Super Weapon',2000,679)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('’Cold Wind’ Kinetic Reaper','Super Weapon',2000,680)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('’Divine Harvest’ Electromagnetic Reaper','Super Weapon',2000,681)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('’Geiravor’ Explosive Lance','Super Weapon',2000,682)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('’Gjallarhorn’ Explosive Doomsday','Super Weapon',2000,683)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('’Guillotine’ Thermal Reaper','Super Weapon',2000,684)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('’Holy Destiny’ Electromagnetic Lance','Super Weapon',2000,685)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('’Iron Pike’ Kinetic Lance','Super Weapon',2000,686)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('’Jormungandr’ Explosive Reaper','Super Weapon',2000,687)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('’Judgment’ Electromagnetic Doomsday','Super Weapon',2000,688)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('’Oblivion’ Kinetic Doomsday','Super Weapon',2000,689)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('’Phalarica’ Thermal Lance','Super Weapon',2000,690)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Bosonic Field Generator','Super Weapon',2000,691)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Gravitational Transportation Field Oscillator','Super Weapon',2000,692)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Pulse Activated Nexus Invulnerability Core','Super Weapon',8000,693)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Survey Probe Launcher I','Survey Probe Launcher',5,694)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Survey Scanner I','Survey Scanner',5,695)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Target Painter I','Target Painter',5,696)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Amarr Phenomena Generator','Titan Phenomena Generator',8000,697)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Caldari Phenomena Generator','Titan Phenomena Generator',8000,698)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Gallente Phenomena Generator','Titan Phenomena Generator',8000,699)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Minmatar Phenomena Generator','Titan Phenomena Generator',8000,700)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Tracking Computer I','Tracking Computer',5,701)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Tracking Enhancer I','Tracking Enhancer',5,702)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Capital Tractor Beam I','Tractor Beam',1000,703)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Small Tractor Beam I','Tractor Beam',50,704)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Experimental Hyperspatial Accelerator','Warp Accelerator',5,705)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Limited Hyperspatial Accelerator','Warp Accelerator',5,706)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Prototype Hyperspatial Accelerator','Warp Accelerator',5,707)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Warp Core Stabilizer I','Warp Core Stabilizer',5,708)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Warp Disruption Field Generator I','Warp Disrupt Field Generator',50,709)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Heavy Warp Disruptor I','Warp Scrambler',100,710)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Heavy Warp Scrambler I','Warp Scrambler',100,711)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Warp Disruptor I','Warp Scrambler',5,712)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Warp Scrambler I','Warp Scrambler',5,713)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Guidance Disruptor I','Weapon Disruptor',5,714)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Tracking Disruptor I','Weapon Disruptor',5,715)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Naga','Attack Battlecruiser',15000,716)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Oracle','Attack Battlecruiser',15000,717)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Talos','Attack Battlecruiser',15000,718)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Tornado','Attack Battlecruiser',15000,719)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Abaddon','Battleship',50000,720)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Apocalypse','Battleship',50000,721)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Armageddon','Battleship',50000,722)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Dominix','Battleship',50000,723)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Hyperion','Battleship',50000,724)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Maelstrom','Battleship',50000,725)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Megathron','Battleship',50000,726)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Praxis','Battleship',50000,727)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Raven','Battleship',50000,728)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Rokh','Battleship',50000,729)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scorpion','Battleship',50000,730)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Tempest','Battleship',50000,731)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Typhoon','Battleship',50000,732)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Rorqual','Capital Industrial Ship',1300000,733)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Archon','Carrier',1300000,734)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Chimera','Carrier',1300000,735)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Nidhoggur','Carrier',1300000,736)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Thanatos','Carrier',1300000,737)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Brutix','Combat Battlecruiser',15000,738)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Cyclone','Combat Battlecruiser',15000,739)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Drake','Combat Battlecruiser',15000,740)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Ferox','Combat Battlecruiser',15000,741)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Gnosis','Combat Battlecruiser',15000,742)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Harbinger','Combat Battlecruiser',15000,743)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Hurricane','Combat Battlecruiser',15000,744)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Myrmidon','Combat Battlecruiser',15000,745)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Prophecy','Combat Battlecruiser',15000,746)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Arbitrator','Cruiser',10000,747)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Augoror','Cruiser',10000,748)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Bellicose','Cruiser',10000,749)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Blackbird','Cruiser',10000,750)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Caracal','Cruiser',10000,751)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Celestis','Cruiser',10000,752)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Exequror','Cruiser',10000,753)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Maller','Cruiser',10000,754)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Moa','Cruiser',10000,755)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Omen','Cruiser',10000,756)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Osprey','Cruiser',10000,757)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Rupture','Cruiser',10000,758)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Scythe','Cruiser',10000,759)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Stabber','Cruiser',10000,760)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Thorax','Cruiser',10000,761)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Vexor','Cruiser',10000,762)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Algos','Destroyer',5000,763)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Catalyst','Destroyer',5000,764)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Coercer','Destroyer',5000,765)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Corax','Destroyer',5000,766)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Cormorant','Destroyer',5000,767)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Dragoon','Destroyer',5000,768)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Sunesis','Destroyer',5000,769)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Talwar','Destroyer',5000,770)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Thrasher','Destroyer',5000,771)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Moros','Dreadnought',1300000,772)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Naglfar','Dreadnought',1300000,773)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Phoenix','Dreadnought',1300000,774)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Revelation','Dreadnought',1300000,775)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Apostle','Force Auxiliary',1300000,776)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Lif','Force Auxiliary',1300000,777)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Minokawa','Force Auxiliary',1300000,778)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Ninazu','Force Auxiliary',1300000,779)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Fenrir','Freighter',1300000,780)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Obelisk','Freighter',1300000,781)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Providence','Freighter',1300000,782)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Atron','Frigate',2500,783)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Bantam','Frigate',2500,784)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Breacher','Frigate',2500,785)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Burst','Frigate',2500,786)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Condor','Frigate',2500,787)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Crucifier','Frigate',2500,788)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Executioner','Frigate',2500,789)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Griffin','Frigate',2500,790)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Heron','Frigate',2500,791)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Imicus','Frigate',2500,792)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Incursus','Frigate',2500,793)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Inquisitor','Frigate',2500,794)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Kestrel','Frigate',2500,795)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Magnate','Frigate',2500,796)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Maulus','Frigate',2500,797)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Merlin','Frigate',2500,798)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Navitas','Frigate',2500,799)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Probe','Frigate',2500,800)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Punisher','Frigate',2500,801)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Rifter','Frigate',2500,802)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Slasher','Frigate',2500,803)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Tormentor','Frigate',2500,804)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Tristan','Frigate',2500,805)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Venture','Frigate',2500,806)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Vigil','Frigate',2500,807)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Badger','Hauler',20000,808)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Bestower','Hauler',20000,809)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Epithal','Hauler',20000,810)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Hoarder','Hauler',20000,811)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Iteron Mark V','Hauler',20000,812)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Kryos','Hauler',20000,813)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Mammoth','Hauler',20000,814)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Miasmos','Hauler',20000,815)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Nereus','Hauler',20000,816)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Primae','Hauler',20000,817)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Sigil','Hauler',20000,818)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Tayra','Hauler',20000,819)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Wreathe','Hauler',20000,820)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Covetor','Mining Barge',3750,821)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Procurer','Mining Barge',3750,822)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Retriever','Mining Barge',3750,823)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Amarr Shuttle','Shuttle',500,824)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Caldari Shuttle','Shuttle',500,825)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Gallente Shuttle','Shuttle',500,826)
INSERT INTO T1Product(T1Name,T1Group,T1Size,T1BPID) VALUES('Minmatar Shuttle','Shuttle',500,827)
